#!/bin/bash

# debug
# set -x

# For local testing ONLY
# OPENSHIFT_DATA_DIR="/dev/shm/os/data/"
# OPENSHIFT_REPO_DIR="${PWD}/"
# OPENSHIFT_TMP_DIR="/dev/shm/os/tmp/"
# OPENSHIFT_DIY_LOG_DIR="/dev/shm/os/log/"

########################################
# BEGIN Configure                      #
########################################
# Racket Version to download and install
VERSION="5.2.1"
RACKET_LAUNCH_PARAMS=""
########################################
# END Configure                        #
########################################

# check needed vars
if [ -z $OPENSHIFT_REPO_DIR ]; then
    echo "Error: OPENSHIFT_REPO_DIR not defined"
    return 1
fi

if [ -z $OPENSHIFT_DATA_DIR ]; then
    echo "Error: OPENSHIFT_DATA_DIR not defined"
    return 1
fi

if [ -z $OPENSHIFT_TMP_DIR ]; then
    echo "Error: OPENSHIFT_TMP_DIR not defined"
    return 1
fi

if [ -z $OPENSHIFT_DIY_LOG_DIR ]; then
    echo "Error: OPENSHIFT_DIY_LOG_DIR not defined"
    return 1
fi

# validate version
if [ "$VERSION" \< "5.2.1" ]; then
    echo "Error: version $VERSION not supported, use version 5.2.1 or higher"
    return 1
fi

LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}system.out"

return 0
