#!/bin/bash

# debug
# set -x

# For local testing ONLY
# OPENSHIFT_DATA_DIR="/dev/shm/os/data/"
# OPENSHIFT_REPO_DIR="${PWD}/"
# OPENSHIFT_TMP_DIR="/dev/shm/os/tmp/"
# OPENSHIFT_DIY_LOG_DIR="/dev/shm/os/log/"

########################################
# BEGIN Configure                      #
########################################
# Racket Version to download and install
RACKET_VERSION="6.0.1"
RACKET_LAUNCH_PARAMS=""
########################################
# END Configure                        #
########################################

# check needed vars
if [ -z $OPENSHIFT_REPO_DIR ]; then
    echo "Error: OPENSHIFT_REPO_DIR not defined"
    return 1
fi

if [ -z $OPENSHIFT_DATA_DIR ]; then
    echo "Error: OPENSHIFT_DATA_DIR not defined"
    return 1
fi

if [ -z $OPENSHIFT_TMP_DIR ]; then
    echo "Error: OPENSHIFT_TMP_DIR not defined"
    return 1
fi

if [ -z $OPENSHIFT_DIY_LOG_DIR ]; then
    echo "Error: OPENSHIFT_DIY_LOG_DIR not defined"
    return 1
fi

# validate version
if [ "$RACKET_VERSION" \< "6.0.1" ]; then
    echo "Error: version $RACKET_VERSION not supported, use version 6.0.1 or higher"
    return 1
fi

LOG_FILE="${OPENSHIFT_DIY_LOG_DIR}system.out"

#racket will be installed here
RACKET_HOME="${OPENSHIFT_DATA_DIR}racket-${RACKET_VERSION}"

#arc will be installed here
ARC_HOME="${OPENSHIFT_DATA_DIR}arc"

return 0
