#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080

#loads Racket RACKET_VERSION, INIT_FILE, LOG_FILE, RACKET_COMMAND
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
    exit $?
fi

${OPENSHIFT_REPO_DIR}.openshift/action_hooks/racket.rc start
