#!/bin/bash
# The logic to stop your application should be put in this script.

#loads Racket RACKET_VERSION, INIT_FILE, LOG_FILE, RACKET_COMMAND
. ${OPENSHIFT_REPO_DIR}.openshift/action_hooks/load_config

if [[ ! $? -eq 0 ]]; then
    exit $?
fi

${OPENSHIFT_REPO_DIR}.openshift/action_hooks/arc.rc stop
